version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: rust_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "Airdrop!@#$5678"
      MYSQL_DATABASE: airdrop
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:6.2
    container_name: rust_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  mysql_data:
  redis_data: