[server]
host = "127.0.0.1"
port = 8080
debug = true

[mysql]
host = "127.0.0.1"
port = 3306
user = "root"
password = "Airdrop!@#$5678"
database = "airdrop"
pool_max_size = 10
pool_min_size = 5
connect_timeout = 5
idle_timeout = 300
max_lifetime = 3600

[redis]
host = "127.0.0.1"
port = 6379
user = ""
password = ""
db = 1
use_tls = false
pool_max_size = 10
pool_min_size = 2
connect_timeout = 5
idle_timeout = 300
max_lifetime = 3600

[jwt]
secret = ""
expiration = 86400

[log]
level = "info"
dir = "./logs"
file = "daily.log"
rotation = "daily"
max_days = 7
console = true